### ISSUE TITLE
link to user/admin dashboard

### ISSUE THREAD

**Issue by memcmahon** [memcmahon/bike-share#106]
when a user is logged in, have a link to their profile/dashboard

**Comment by AtmaVichara** [comment]
The bike icon could lead back to the users/admins dashboard. Keep the visitor in mind. They shouldn't be able to go to those dashboards. Maybe if they try send them to the home screen or 404

**Comment by garcia50** [comment]
I think that having the bike icon to lead to the users/admins dashboard might be a little confusing for a user to know/understand what that is(if its even a link or naw), I just read these messages btw...I have actually already created a simple "Account" link in the nav for the user/admin. I would also suggest preserving the bike icon for an actual welcome page to our site. Of course we can def change anything to what think makes more sense... my styling and sense of UX is horrible to begin with hahaha.. just lmk
