### ISSUE TITLE
Registered User - visit "/cart" Index functionality(i.e. "Checkout" button)

### ISSUE THREAD

**Issue by garcia50** [memcmahon/bike-share#45]

**Comment by garcia50** [comment]
As a registered user,
When I visit "/",
I see a link for "Login",

When I click "Login",
I should be on the "/login" page,
I see a place to insert my credentials to login,
I fill in my desired credentials,
I submit my information,
My current page should be "/dashboard",
I see a message in the navbar that says "Logged in as SOME_USER",
I see my profile information,
I do not see a link for "Login",
I see a link for "Logout".

**Comment by AtmaVichara** [comment]
As a registered user,
After adding a few items to my cart,
When I visit '/cart',
And click "Checkout",
I see my own dashboard,
I also see a flash message telling me I have "successfully submitted your order".
